FROM registry.access.redhat.com/ubi9/ubi-init:latest

# install tailscale
RUN dnf copr enable -y \
	    jonathanspw/headscale \
    && dnf install -y \
        headscale \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && systemctl enable headscale

# No need for entrypoint as base sets this
#ENTRYPOINT ["/sbin/init"]